credentials:
  usernames:
    premium:
      name: PremiumUser
      password: "$2b$12$uYmvkBGiT9V7YxuDeU6FaeSG.yB3zNCUWLMTPjxvclVxprdf9JoPG"
cookie:
  name: sharpedge_cookie
  key: secret_key
  expiry_days: 7
preauthorized:
  emails: []
